Update to latest schnorr bip340
p2pderivatives/p2pderivatives-oracle pull request #18
Opened 2020-10-20 07:09 UTC by Tibo-lg

Update to cfd-go to use the latest bip340 specifications for Schnorr signatures.

2020-10-21 10:04 UTC, prunelsigma requested changes
LGTM just some questions

2020-10-21 10:04 UTC, prunelsigma commented on internal/dlccrypto/cfdgo_crypto_service.go
> -		return nil, errors.WithMessage(err, "Error while generating one time signing K")
You removed the error message the default will be ok ?

2020-10-21 10:04 UTC, prunelsigma commented on internal/dlccrypto/cfdgo_crypto_service_test.go
> +	rand.Seed(time.Now().UnixNano())
Not really important since it's not cfdgo unit-testing but you could keep the seed in the log/output to allow reproducible test

2020-10-21 12:48 UTC, Tibo-lg commented on internal/dlccrypto/cfdgo_crypto_service.go
> -		return nil, errors.WithMessage(err, "Error while generating one time signing K")
Good point re-added (different one)

2020-10-21 12:48 UTC, Tibo-lg commented on internal/dlccrypto/cfdgo_crypto_service_test.go
> +	rand.Seed(time.Now().UnixNano())
Done

2020-10-23 01:05 UTC, prunelsigma requested changes
just one error removed left, otherwise fine

2020-10-23 01:05 UTC, prunelsigma commented on internal/dlccrypto/cfdgo_crypto_service.go
> +		return nil, nil, err
also here

2020-10-23 01:44 UTC, Tibo-lg commented on internal/dlccrypto/cfdgo_crypto_service.go
> +		return nil, nil, err
Thanks fixed

2020-10-23 02:29 UTC, prunelsigma approved these changes
LGTM

2020-10-23 02:32 UTC, merged